version: "3.8"
services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command:
      - "web"
  worker:
    build:
      dockerfile: Dockerfile
      context: .
    command:
      - "worker"
  database:
    image: postgres:13-alpine
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root