"""add pin

Revision ID: 009f245ce40e
Revises: cc1c62a9c113
Create Date: 2021-04-12 21:20:25.068072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009f245ce40e'
down_revision = 'cc1c62a9c113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actuator_binary', sa.Column('pin', sa.String(), server_default='INSERT_PIN_HERE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actuator_binary', 'pin')
    # ### end Alembic commands ###
