"""empty message

Revision ID: 34b03b01fc8f
Revises: 
Create Date: 2020-11-01 21:37:29.254101

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b03b01fc8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('uuid', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
    sa.Column('type', sa.Enum('extended_user', name='account_types'), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('type', 'value', name='type_value')
    )
    op.create_index(op.f('ix_accounts_type'), 'accounts', ['type'], unique=False)
    op.create_index(op.f('ix_accounts_value'), 'accounts', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_value'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_type'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
