"""empty message

Revision ID: 3eaa261ad7a5
Revises: 82dc3045e6ff
Create Date: 2020-11-18 12:10:00.019591

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '3eaa261ad7a5'
down_revision = '82dc3045e6ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('url', sa.String(), nullable=False),
                    sa.Column('is_online', sa.Boolean(), nullable=False),
                    sa.Column('last_time_was_saw_online', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('url')
                    )
    op.create_index(op.f('ix_hosts_created_at'), 'hosts', ['created_at'], unique=False)
    op.create_index(op.f('ix_hosts_last_time_was_saw_online'), 'hosts', ['last_time_was_saw_online'], unique=False)
    op.create_index(op.f('ix_hosts_updated_at'), 'hosts', ['updated_at'], unique=False)
    op.create_table('ds_host_relation',
                    sa.Column('host', sa.String(), nullable=True),
                    sa.Column('device', sqlalchemy_utils.types.uuid.UUIDType(), nullable=True),
                    sa.ForeignKeyConstraint(['device'], ['device_switch.identifier'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['host'], ['hosts.url'], ondelete='CASCADE')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ds_host_relation')
    op.drop_index(op.f('ix_hosts_updated_at'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_last_time_was_saw_online'), table_name='hosts')
    op.drop_index(op.f('ix_hosts_created_at'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
