"""empty message

Revision ID: 82dc3045e6ff
Revises:
Create Date: 2020-11-15 12:49:25.526884

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

# revision identifiers, used by Alembic.
revision = '82dc3045e6ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_switch',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('identifier', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False),
                    sa.Column('is_on', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('identifier')
                    )
    op.create_index(op.f('ix_device_switch_created_at'), 'device_switch', ['created_at'], unique=False)
    op.create_index(op.f('ix_device_switch_updated_at'), 'device_switch', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_switch_updated_at'), table_name='device_switch')
    op.drop_index(op.f('ix_device_switch_created_at'), table_name='device_switch')
    op.drop_table('device_switch')
    # ### end Alembic commands ###
