"""empty message

Revision ID: cc1c62a9c113
Revises: 3eaa261ad7a5
Create Date: 2020-11-21 13:46:00.392733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1c62a9c113'
down_revision = '3eaa261ad7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_switch', sa.Column('name', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_switch', 'name')
    # ### end Alembic commands ###
